version: 0.2

env:
  secrets-manager:
    SSH_KEY: "ec2-ssh-key"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "$SSH_KEY" > key.pem
      - chmod 400 key.pem

  build:
    commands:
      - echo "Deploying to EC2..."
      - ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@13.62.229.150 "
          cd /home/ec2-user/auth-backend &&
          git pull &&
          npm install &&
          npm run build &&
          pm2 restart backend
        "
