version: 0.2

env:
  secrets-manager:
    SSH_KEY: "ec2-ssh-key"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "$SSH_KEY" > key.pem
      - chmod 400 key.pem
      - npm install

  build:
    commands:
      - npm run build

  post_build:
  commands:
    - eval $(ssh-agent -s)
    - ssh-add key.pem
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - scp -r . ec2-user@13.49.49.161:/home/ec2-user/app
    - ssh ec2-user@13.49.49.161 "cd /home/ec2-user/app && npm install && pm2 restart all"
